### ISSUE TITLE
Allow paying with Edenred

### ISSUE THREAD

**Issue by shikaruko** [coopcycle/coopcycle-app#1131] opened 2021-06-24 20:56 UTC
![edenred coopcycle](https://user-images.githubusercontent.com/13643289/124360471-518f1200-dc2a-11eb-930f-7cbe5a6b8b0d.png)
![tickets resto coopcycle](https://user-images.githubusercontent.com/13643289/124360452-2f958f80-dc2a-11eb-86d4-8caeadf5b679.png)
**Describe the bug**
I am a customer on Sicklo. From few times ago, it allow to pay with restaurant tickets card and on the web an icon show the restaurant where we can use this kind of payment. On the app we can't see it.

**Expected behavior**
A same view of the both tools

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: CAT S41
 - OS: Android 8.0

**Additional context**

**Comment by AdrienSICKLO** [comment] 2021-07-05 15:06
Hi @shikaruko 
Its on the roadmap but as for now, it is not yet possible to pay with Tickets restaurants through the app!

**Comment by ERAMANrepartos** [comment] 2023-04-28 12:04
@alexsegura is this the same issue, or just related to https://github.com/coopcycle/coopcycle-web/issues/3153?

**Comment by alexsegura** [comment] 2024-07-05 09:23
Duplicate of #1775

**Closed by alexsegura** 2024-07-05 09:23 UTC
