### ISSUE TITLE
App crashes when customer changes delivery date

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-app#1520] opened 2023-06-26 17:11 UTC
**Describe the bug**
As a customer, I choose my restaurant, food and go to checkout. On the order summary, I want to change delivery date for another day. This last action crashes the app instantly

**To Reproduce**
1. Make an order
2. Go to cart summary
3. click on date to change it

**Expected behavior**
Customer should have a choice of dates 

**Screenshots**

https://github.com/coopcycle/coopcycle-app/assets/11749973/070bd6f1-4700-4c89-ad18-8edef37e3453

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
  - OS: Android 9
 - Browser None
 - App version 2.7.1

**Additional context**

**Comment by r0xsh** [comment] 2023-07-04 07:31
Thanks for your report, the bug has been fixed and should be deployed in the following days.

Duplicate of #1505

**Closed by r0xsh** 2023-07-04 07:31 UTC
Labels: bug
