### ISSUE TITLE
As a consumer I can order a zero-waste delivery without paying the deposit through IMPEC

### ISSUE THREAD

**Issue by impec-dev** [coopcycle/coopcycle-app#1584] opened 2023-10-30 10:57 UTC
**Describe the bug**
On the app, I can select the reusable packaging without connecting to IMPEC hence without paying the deposit for the container

**To Reproduce**
1. Go to a restaurant page which offer zero waste delivery and make a cart with dish which qualify for zero-waste delivery
2. Click on 'I want reusable container"
3. Do NOT connect to IMPEC
4. You can finalize the order

**Expected behavior**
You must not be able to finish you order if : 
- the deposit is not paid
- or you return enough container to balance the deposit of the order
- or you cancel the reusable packaging option

**Screenshots**

https://github.com/coopcycle/coopcycle-app/assets/83373118/7b16c64f-9f0a-4474-ba63-7477a2394761

**Smartphone (please complete the following information):**
 - Device: Huawei P30 pro
 - OS: 12.0.0.149
 - Browser chrome (but on the app...)

**Additional context**

**Comment by alexsegura** [comment] 2023-10-31 14:46
Duplicate of #1582

**Closed by alexsegura** 2023-10-31 14:46 UTC
Labels: bug, zero-waste
