### ISSUE TITLE
 automatic date refresh

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-app#1128] opened 2021-06-22 16:38 UTC
automatic date refresh for restaurants

**Comment by agichim** [comment] 2021-06-22 23:25
Hi @Carlitofastandcurious 

Can you explain in more detail what exactly you need or the issue is?

**Comment by Carlitofastandcurious** [comment] 2021-06-23 08:19
Most of the time, restaurants are never on the right date on their order board (new order, order accepted, order completed, order canceled). The date at the top right is rarely the current day.

**Comment by ERAMANrepartos** [comment] 2023-04-28 12:11
This appears fixed in current deployment, closing

**Closed by ERAMANrepartos** 2023-04-28 12:11 UTC
Labels: enhancement
