### ISSUE TITLE
Giving address shows no results

### ISSUE THREAD

**Issue by pessi-v** [coopcycle/coopcycle-app#865] opened 2020-11-20 20:14 UTC
**Describe the bug**
Putting an address shows no results, for an address that should have results (in Berlin Neukölln)

**To Reproduce**
Open Coopcycle 1.4.0 on Android. Have internet connection. Enter address in the first view, receive no results

**Expected behavior**
A list of restaurants

**Screenshots**
-

**Desktop (please complete the following information):**
 - LineageOS 16 (Android)

**Smartphone (please complete the following information):**
 - Sony Xperia XC

**Comment by amadsalmon** [comment] 2021-01-24 22:24
It would be nice to include more details, for instance the address that gave no results.

**Comment by pessi-v** [comment] 2021-01-26 09:00
@amadsalmon I've updated now to the latest and tried again. Still the same issue: no results for any addresses in Berlin

**Comment by alexsegura** [comment] 2021-01-26 09:19
Hi, 

On the app we still use Google Maps APIs for address suggestions (see [AddressAutocomplete](https://github.com/coopcycle/coopcycle-app/blob/4339eae66c2a7769213d11d4216950b4c1a997b0/src/components/AddressAutocomplete.js#L131)). 
For sure there are lots of problems on the app, but lots of people are indeed entering their address successfully in Berlin. 

So I suspect the problem is specific to you, @pessi-v. 
Is it possible that you have _something_ that blocks Google APIs?

Another thing that can explain the problem is that we restrict results to a radius of 50km around the center of the city. 
The exact query is built like this:

https://github.com/coopcycle/coopcycle-app/blob/4339eae66c2a7769213d11d4216950b4c1a997b0/src/components/AddressAutocomplete.js#L182-L196

**Comment by pessi-v** [comment] 2021-01-26 09:26
@alexsegura I don't have issues with other apps that use Google APIs, but it's possible that Lineage OS comes with something that breaks the Google services or that Google checks if the OS is legit.

The addresses I tried are definitely within the radius of participating restaurants and did indeed work before.

**Comment by ERAMANrepartos** [comment] 2023-04-28 18:34
This appears to be a specific issue, closing

**Closed by ERAMANrepartos** 2023-04-28 18:34 UTC
Labels: bug
