### ISSUE TITLE
Task list's settings button does not appear in light mode

### ISSUE THREAD

**Issue by vingt-douze** [coopcycle/coopcycle-app#1762] opened 2024-04-19 10:35 UTC
| Light | Dark |
|-|-|
| ![](https://github.com/coopcycle/coopcycle-app/assets/90503814/820b503e-ac56-40c3-835f-569805536213) | ![](https://github.com/coopcycle/coopcycle-app/assets/90503814/03344041-fa9a-46f2-add8-0bed8f202c03) |

**Comment by Pierre-LHOSTE** [comment] 2024-04-23 13:50
Duplicate of https://github.com/coopcycle/coopcycle-app/issues/1741

**Closed as completed by Pierre-LHOSTE** 2024-04-23 13:50 UTC
Labels: bug
